#! /usr/bin/env python3

import glob
import datetime
import sys
import os.path
import invoices


def main(match=''):
    total = 0
    for filename in sorted(glob.glob('data/*.ini')):
        invoice = invoices.Invoice(filename)
        if match not in invoice.invoice['item'].lower() and match not in invoice.invoice['contact'].lower():
            continue
        print('{0}: {1} {2} ({4:.2f} CZK): {3}'.format(
            invoice.invoiceid,
            invoice.amount,
            invoice.currency,
            invoice.invoice['item'],
            invoice.amount_czk,
        ))
        total += invoice.amount_czk
    print()
    print('Total: {0:.2f} CZK'.format(total))


if __name__ == '__main__':
    main(*sys.argv[1:])
