#! /usr/bin/env python3

import glob
import datetime
import sys
import os.path
import invoices



def main(year=None):
    if year is None:
        year = datetime.date.today().year
    else:
        year = int(year)

    if year > 2000:
        year = year - 2000

    supertotal = 0
    mask = 'data/{0}*.ini'.format(year)
    for filename in sorted(glob.glob(mask)):
        invoice = invoices.Invoice(filename)
        if not invoice.paid():
            print('{0}: {1} {2}'.format(
                invoice.invoiceid,
                invoice.amount,
                invoice.currency
            ))


if __name__ == '__main__':
    main(*sys.argv[1:])

