# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-xml
    -   id: check-toml
    -   id: requirements-txt-fixer
    -   id: check-merge-conflict
    -   id: check-json
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: sort-simple-yaml
    -   id: mixed-line-ending
        args: [--fix=lf]
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        additional_dependencies:
        - flake8-breakpoint
        - flake8-black
        - flake8-bugbear
        - flake8-builtins
        - flake8-comprehensions
        - flake8-django
        - flake8-docstrings
        - flake8-eradicate
        - flake8-executable
        - flake8-isort
        - flake8-logging-format
        - flake8-mutable
        - flake8-no-u-prefixed-strings
        - flake8-print
        - flake8-return
        - flake8-self
        - flake8-string-format
        - pep8-naming
