# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.0.284"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-xml
    -   id: check-toml
    -   id: requirements-txt-fixer
    -   id: check-merge-conflict
    -   id: check-json
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: sort-simple-yaml
    -   id: mixed-line-ending
        args: [--fix=lf]
