[tool.isort]
profile = "black"

[tool.ruff]
output-format = "github"
target-version = "py311"

[tool.ruff.lint]
ignore = [
  "EM102",
  "D211",
  "D212",
  "D10",
  "T201",
  "TRY003",
  "PTH",
  "ANN",
  "DTZ011",
  "EM101",
  "S607",
  "S603",
  "S310",
  "S701",
  "S101"
]
select = ["ALL"]

[tool.ruff.lint.mccabe]
max-complexity = 16
