[tool.isort]
profile = "black"

[tool.ruff]
ignore = ["D211", "D212", "D10", "T201", "TRY003"]
select = ["E", "F", "B", "T10", "A", "C4", "C90", "YTT", "DJ", "UP", "D", "PD", "PGH", "PL", "TRY", "RUF", "ERA", "ICN", "ISC", "EXE", "INP", "PIE", "G", "PYI", "Q", "SIM", "TID", "RSE", "T20", "RET", "SLF", "N"]
target-version = "py39"
format = "github"

[tool.ruff.per-file-ignores]

[tool.ruff.mccabe]
max-complexity = 16
