name: Lint

on: [push, pull_request]

jobs:
  ruff:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - uses: astral-sh/setup-uv@v3
    - name: Install dependencies
      run: uv pip install -r requirements-test.txt
    - name: pre-commit
      env:
        RUFF_OUTPUT_FORMAT: github
        REUSE_OUTPUT_FORMAT: github
      run: pre-commit run --all
