name: Distribution

on: [push, pull_request]

jobs:
  setup:

    runs-on: ubuntu-latest
    permissions:
      # this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-setup-${{ hashFiles('**/requirements*.txt') }}
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - uses: astral-sh/setup-uv@v3
    - name: Install dependencies
      run: uv pip install --system -r requirements-test.txt
    - name: build
      run: uv build
    - name: twine check
      run: uvx twine check --strict dist/*
    - name: pydistcheck
      run: uvx pydistcheck --inspect dist/*
    - name: pyroma
      run: uvx pyroma dist/*.tar.gz
    - name: check-wheel-contents
      run: uvx check-wheel-contents dist/*.whl
    - name: check-manifest
      run: uvx check-manifest -v
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      run: uv publish --trusted-publishing always
