name: Distribution

on: [push, pull_request]

jobs:
  setup:

    runs-on: ubuntu-latest
    permissions:
      # this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-setup-${{ hashFiles('**/requirements*.txt') }}
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - uses: astral-sh/setup-uv@v3
    - name: Install dependencies
      run: uv pip install -r requirements-test.txt
    - name: build
      run: uv build
    - name: twine
      run: twine check --strict dist/*
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      run: uv publish --trusted-publishing always
